### ISSUE TITLE
Why get-caller-file only allow 6.x || 8.x|| >= 10.x ndoe.js version

### ISSUE THREAD

**Issue by stu01509** [stefanpenner/get-caller-file#18]
Why reason get-caller-file only allow 6.x, 8.x, or above 10.x node.js version?

**Comment by mr-dxdy** [comment]
+1

**Comment by stefanpenner** [comment]
Ya, we mirror Node's own support policies. We don't have resources to support versions of node that node does not support, for more details on what node's own support policy is: https://github.com/nodejs/Release.

To disable the warning/error yarn provides, feel free to use `yarn install --ignore-engines`
